export enum AiOpinion {
  SPAM = 'SPAM',
  OFFENSIVE = 'OFFENSIVE',
  APPROPRIATE = 'APPROPRIATE',
  IRRELEVANT = 'IRRELEVANT',
  HARASSMENT = 'HARASSMENT',
  POSITIVE = 'POSITIVE',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  OTHER = 'OTHER'
}
